version: '3'
services:
  leona-tbed:
    build:
      context: leona-fe
      dockerfile: Dockerfile
    container_name: leona-tbed
    ports:
      - "8081:8081"
    volumes:
      - ./leona/storage:/storage
      - ./leona/logs:/logs
      - ./leona/backup:/backup
      - /etc/localtime:/etc/localtime
    networks:
      - leona
    restart: always
networks:
  leona:
    # driver: bridge
    external: true